website/docs: add new content from old PR #9524
goauthentik/authentik pull request #10158
Opened 2024-06-18 21:07 UTC by tanberry

This new content with steps about how to add a custom LDAP property mapping is thanks to @ChenWenBrian who originally opened PR #9524, but due to me not looking at it earlier and it getting completely stale, past the point of manageable merge conflicts, I have recreated his PSR here.

-   [ ] The documentation has been updated
-   [ ] The documentation has been formatted (`make website`)

2024-06-19 13:31 UTC, rissson commented
Let's add a `Co-authored-by: "Brian, Chen" <wildfox@126.com>` when merging.

2024-06-19 15:35 UTC, dominic-r requested changes

2024-07-03 21:26 UTC, tanberry commented
@marc can you take a look at the `lint(black)` and `lint(ruff)` check fails? I'm not sure why a .py file is being discussed, lol?

If it's a check we can safely ignore, please approve PR and I'll get it merged. Thanks!

2024-07-05 15:49 UTC, rissson approved these changes

2024-07-05 15:49 UTC, BeryJu commented on website/docs/sources/ldap/index.md
> +For example, the setting `ldap-displayName-mapping:name` means that the LDAP source field `displayName` will be mapped to the `name` field in authentik.
```suggestion
```

2024-07-05 15:49 UTC, merged

2024-07-05 15:49 UTC, rissson commented on website/docs/sources/ldap/index.md
> +For example, the setting `ldap-displayName-mapping:name` means that the LDAP source field `displayName` will be mapped to the `name` field in authentik.
ah