Update nginx docs for embedded outposts.
goauthentik/authentik pull request #10422
Opened 2024-07-09 16:16 UTC by fotinakis

A followup to https://github.com/goauthentik/authentik/pull/10181 — that docs PR was partially correct, but does not work for the embedded outpost.

The way it works is:
* Manual outpost: when traffic flows to the proxy `/outpost.goauthentik.io/<PATH>` path, it should be stripped off and then sent to `outpost:company:9000/<PATH>`  (this is what the docs show now)
* Embedded outpost: when traffic flows to the proxy `/outpost.goauthentik.io/<PATH>` nginx proxy must prepend this path back again when sending it to the embedded outpost at `authentik.company:9000/outpost.goauthentik.io/<PATH>`

This PR clarifies how to make it work for both cases.

2024-07-09 16:32 UTC, tanberry commented
Thanks so much for this contribution, @fotinakis ! We will get a tech review on it and get it merged.

2024-07-09 16:42 UTC, rissson requested changes

2024-07-09 16:42 UTC, rissson commented on website/docs/providers/proxy/_nginx_proxy_manager.md
> +    proxy_set_header        Host $host;
This line is already present just below

2024-07-09 18:25 UTC, fotinakis commented on website/docs/providers/proxy/_nginx_proxy_manager.md
> +    proxy_set_header        Host $host;
Fixed

2024-07-10 14:24 UTC, rissson approved these changes

2024-07-11 10:37 UTC, BeryJu reviewed
The PR looks good, but I'm a bit confused as needing two different configuration settings shouldn't be required, since the code for the routing is identical between embedded and standalone outpost

2024-07-11 15:07 UTC, rissson commented
> The PR looks good, but I'm a bit confused as needing two different configuration settings shouldn't be required, since the code for the routing is identical between embedded and standalone outpost

I think the idea is just to point out that specifically for the embedded outpost, you need to point the reverse proxy to the authentik server

2024-07-15 18:14 UTC, BeryJu commented
> > The PR looks good, but I'm a bit confused as needing two different configuration settings shouldn't be required, since the code for the routing is identical between embedded and standalone outpost
> 
> I think the idea is just to point out that specifically for the embedded outpost, you need to point the reverse proxy to the authentik server

That part makes sense, but either both of them should have `/outpost.goauthentik.io` or `/` as path, there shouldn't be a difference as the URL handling is the same in both outpost modes. I haven't tested this myself cc @fotinakis

2024-07-23 19:05 UTC, fotinakis commented
@BeryJu (sorry, missed this PR notification) — I actually did test this and found experimentally it is correct. It makes sense from this perspective: a standalone outpost accepts outpost traffic at `/*`, but the authentik server accepts outpost traffic at `/outpost.goauthentik.io/*` — so if you stick an nginx proxy in front of your app, you must differentiate where it is sending outpost traffic depending on if you're using standalone or embedded outposts.

You could potentially hide this behavior by making standalone outposts also accept traffic with the `/outpost.goauthentik.io/*` prefix — then you could condense these configs down to one because no path transformation would be necessary.

2024-07-30 14:13 UTC, fotinakis commented
@BeryJu this was approved by @rissson  — can you guys help get this merged before it gets stale? Thank you!

2024-07-30 14:24 UTC, merged