website/integrations: add Observium documentation
goauthentik/authentik pull request #10460
Opened 2024-07-11 19:34 UTC by Simi23

## Details

This PR adds a configuration guide for Observium as an Integration.

---

## Checklist

-   [ ] Local tests pass (`ak test authentik/`)
-   [x] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [ ] The code has been formatted (`make web`)

If applicable

-   [x] The documentation has been updated
-   [x] The documentation has been formatted (`make website`)

2024-07-11 22:06 UTC, tanberry commented
Thanks so much @Simi23 for this contribution, much appreciated! I have not done a good job of getting the word out about our new-ish [template for Integrations](https://github.com/goauthentik/authentik/blob/main/website/integrations/template/service.md); we are trying to get all of our Integrations docs to follow the same structure and use the same Headers, etc. 

If you're up for it, please restructure it to follow the template. Or I can, if you prefer. Also, question... are mod_auth_openidc and Apache requirements? Should they maybe be listed first under Preparation?

Or is it necessary to do it in the order you have, to create the authentik app/provider before configuring Apache?

2024-07-12 16:01 UTC, Simi23 commented
Hi @tanberry, thank you for your response! I started with the template which you have linked, but then edited it a bit. I will rework the document so it doesn't differ this much. However, you mentioned the order of the configuration steps. I think authentik should come first because you need the Client ID and the Client Secret when configuring Apache.

> Also, question... are mod_auth_openidc and Apache requirements? Should they maybe be listed first under Preparation?

Good point! I will add those to the Preparation section.

I will also fix the wording issues and commit a new version this evening.

2024-07-12 21:03 UTC, dominic-r requested changes

2024-07-12 21:09 UTC, Simi23 commented on website/integrations/services/observium/index.md
> +This guide assumes you already have a working Observium instance. It is recommended to install it with the install script, following the [instructions](https://docs.observium.org/install_debian/) on
Changing the link to https://docs.observium.org/ might work, as the first two links in there lead to the two install guides. Would that be a good solution?

2024-07-12 21:13 UTC, Simi23 commented on website/integrations/services/observium/index.md
> +    With this method, you can only assign one permission level to all users. Since Observium permits only a single authentication mechanism to be selected, it is recommended to set `auth_remote_userl
Yes, it is intentional, it is to indicate that it belongs to step 2. For me it looks more organized this way.

2024-07-12 21:17 UTC, Simi23 commented on website/integrations/services/observium/index.md
> +    With this method, you can only assign one permission level to all users. Since Observium permits only a single authentication mechanism to be selected, it is recommended to set `auth_remote_userl
I have already ran it :)

2024-07-12 21:18 UTC, dominic-r reviewed
wrong button

2024-07-12 21:18 UTC, dominic-r approved these changes
🚀

2024-07-18 15:05 UTC, tanberry approved these changes
Thanks again @simi23!

2024-07-18 15:05 UTC, merged