Add MeshCentral Integration docs
goauthentik/authentik pull request #10490
Opened 2024-07-13 17:08 UTC by axemann

## Details

This PR adds documentation for integrating authentik with [MeshCentral](https://meshcentral.com).

No API or frontend changes have been made.

---

## Checklist

-   [x] Local tests pass (`ak test authentik/`)
-   [x] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [ ] The code has been formatted (`make web`)

If applicable

-   [x] The documentation has been updated
-   [x] The documentation has been formatted (`make website`)

2024-07-13 19:45 UTC, dominic-r requested changes

2024-07-18 00:07 UTC, tanberry requested changes
Thanks so much @axemann for this contribution. MeshCebtral looks kinda cool! I have a couple of nits and suggestions. Also, I noticed that the build check for `prettier` failed.. can you run `make website` or `npm run prettier` and then push to the PR again? Let me know if you have any questions; here are our docs for how to run the required linting before pushing a PR. https://docs.goauthentik.io/developer-docs/docs/writing-documentation

2024-07-18 00:07 UTC, tanberry commented on website/integrations/services/meshcentral/index.md
> +Create an OAuth2/OpenID provider with the following parameters:
```suggestion
## authentik configuration

Create an OAuth2/OpenID provider with the following parameters:
```

2024-07-18 00:07 UTC, tanberry commented on website/integrations/services/meshcentral/index.md
> +Note the Client ID and Client Secret values. Create an application, using the provider you've created above.
```suggestion
Note the Client ID and Client Secret values. 

Next, create an application, using the provider you've created above.
```

2024-07-18 00:07 UTC, tanberry commented on website/integrations/services/meshcentral/index.md
> +> Remember to follow JSON formatting rules
```suggestion
> Remember to follow JSON formatting rules.
```

2024-07-18 15:57 UTC, tanberry commented on website/integrations/services/meshcentral/index.md
> +> MeshCentral is an open source, multi-platform, self-hosted, feature packed web site for remote device management.
Yeah, we chatted about that... we agreed that one *could do this (and it wouldn't be consider plagiarism, but rather a quote), but it is best to rewrite the description.

2024-07-31 21:50 UTC, tanberry commented
Hi @axemann it seems the `prettier-check` is still failing... were you able to run the formatting command `make website` before pushing the latest commits? If you are doing this work in a local repo, that's this easiest way. Or are you doing this via the GitHub UI?

2025-01-02 14:16 UTC, closed without merging