Add offline_access scope
goauthentik/authentik pull request #11274
Opened 2024-09-07 22:30 UTC by G-Pereira

## Details
The offline_scope is required in order to allow refresh tokens to be generated otherwise the session will expire at Wordpress side.
This is just a documentation contribution.

## Checklist

-   [ ] Local tests pass (`ak test authentik/`)
-   [ ] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [ ] The code has been formatted (`make web`)

If applicable

-   [x] The documentation has been updated
-   [ ] The documentation has been formatted (`make website`)

2024-09-07 23:48 UTC, BeryJu requested changes
The offline_access scope is not selected by default in authentik, so it should be added to the docs under line 37 that the offline_access mapping needs to be selected

2024-09-09 11:39 UTC, G-Pereira commented
Thank you for your review @BeryJu . That's a good idea. Just added it.

2024-09-11 10:37 UTC, BeryJu commented on website/integrations/services/wordpress/index.md
> +-   Scopes: _email_, _offline_access_, _open_id_, _profile_
```suggest
-   Scopes: _email_, _offline_access_, _openid_, _profile_
```

2024-09-11 10:38 UTC, BeryJu approved these changes

2024-09-11 10:44 UTC, merged