Web/policy wizard 3
goauthentik/authentik pull request #11462
Opened 2024-09-20 22:22 UTC by kensternberg-authentik

## Details

REPLACE ME

---

## Checklist

-   [ ] Local tests pass (`ak test authentik/`)
-   [ ] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [ ] The code has been formatted (`make web`)

If applicable

-   [ ] The documentation has been updated
-   [ ] The documentation has been formatted (`make website`)

2024-11-12 23:32 UTC, kensternberg-authentik reviewed
Yeah, that's legit.  :-)

2024-12-13 17:55 UTC, rissson requested changes

2024-12-13 17:55 UTC, rissson commented on web/src/admin/applications/wizard/steps/ak-application-wizard-edit-binding-step.ts
> +        return html`<ak-wizard-title>${msg("Select A Policy Binding")}</ak-wizard-title>
```suggestion
        return html`<ak-wizard-title>${msg("Select A Policy/User/Group Binding")}</ak-wizard-title>
```

2024-12-13 17:55 UTC, rissson commented on web/src/admin/applications/wizard/steps/ak-application-wizard-bindings-step.ts
> +        return html` <ak-wizard-title>${msg("Configure Policy Bindings")}</ak-wizard-title>
```suggestion
        return html` <ak-wizard-title>${msg("Configure Policy/User/Group Bindings")}</ak-wizard-title>
```

2024-12-17 13:04 UTC, BeryJu approved these changes

2024-12-18 17:44 UTC, merged