website/docs: add info about invalidation flow, default flows in general
goauthentik/authentik pull request #11800
Opened 2024-10-24 22:36 UTC by tanberry

DRAFT

This PR adds a new section about default flows, and commonly used flow, and the new invalidation flow.

-   [ ] The documentation has been updated
-   [ ] The documentation has been formatted (`make website`)

2024-10-28 15:05 UTC, BeryJu requested changes

2024-10-28 15:05 UTC, BeryJu commented on website/docs/add-secure-apps/flows-stages/flow/index.md
> +-   **Authentication flow**:
Move explanation to why different flow types need to be configured on a brand level to brand page below

2024-10-30 17:22 UTC, tanberry commented on website/docs/add-secure-apps/flows-stages/flow/index.md
> +There are over a dozen default, out-of-the box flows available in authentik. Users can decide if they already have everything they need with the [default flows](#default-and-commonly-used-flows) or i
Thanks! I added this to my local repo and pushed.

2024-10-31 13:03 UTC, BeryJu approved these changes

2024-10-31 13:26 UTC, merged

2024-11-05 10:04 UTC, gergosimonyi commented
/cherry-pick version-2024.10