website/integrations: vault: add external group documentation
goauthentik/authentik pull request #11994
Opened 2024-11-11 14:31 UTC by mzhaase

## Details

This PR changes the documentation page https://docs.goauthentik.io/integrations/services/hashicorp-vault/.
It adds more in-depth explanation on how to integrate authentik with hashicorp vault when wanting to use external groups.

---

2024-11-11 20:32 UTC, tanberry commented on website/integrations/services/hashicorp-vault/index.md
> +If you wish to manage group membership in vault via Authentik you have to use [external groups](https://developer.hashicorp.com/vault/tutorials/auth-methods/oidc-auth#create-an-external-vault-group).
```suggestion
If you wish to manage group membership in Hashicorp Vault via Authentik you have to use [external groups](https://developer.hashicorp.com/vault/tutorials/auth-methods/oidc-auth#create-an-external-vault-group).
```

2024-11-11 20:35 UTC, tanberry commented on website/integrations/services/hashicorp-vault/index.md
> -If you intend to create [external groups](https://developer.hashicorp.com/vault/tutorials/auth-methods/oidc-auth#create-an-external-vault-group) in Vault to manage user access the OIDC role will need
Does one no longer need to use the `oidc_scopes` option at all?

2024-11-11 20:36 UTC, tanberry commented on website/integrations/services/hashicorp-vault/index.md
> +In hashicorp vault, change the reader role
```suggestion
In Vault, change the reader role to have the following settings:
```

2024-11-11 20:37 UTC, tanberry commented on website/integrations/services/hashicorp-vault/index.md
> +Add a group
```suggestion
Add a group.
```

2024-11-11 20:37 UTC, tanberry commented on website/integrations/services/hashicorp-vault/index.md
> +Get the canonical id of the group
```suggestion
Get the canonical id of the group.
```

2024-11-11 20:39 UTC, tanberry commented on website/integrations/services/hashicorp-vault/index.md
> +Get the canonical id of the group
If this is the canoncal ID, let's add this full name: `vault_identity_group`

2024-11-11 20:39 UTC, tanberry commented on website/integrations/services/hashicorp-vault/index.md
> +Get the id of the oidc accessor
```suggestion
Get the ID of the OIDC accessor.
```

2024-11-11 20:40 UTC, tanberry commented on website/integrations/services/hashicorp-vault/index.md
> +Add a group alias, this maps the group to the oidc backend
```suggestion
Add a group alias; this alias maps the group to the OIDC backend.
```

2024-11-11 20:40 UTC, tanberry commented on website/integrations/services/hashicorp-vault/index.md
>  You should then be able to sign in via OIDC
Can you add a period at end of this sentence, please?

2024-11-11 20:41 UTC, tanberry requested changes
Thanks so much for adding this additional, important info! A couple of edits and suggestions, then let's git it merged! Thanks again.

2024-11-11 20:42 UTC, tanberry commented
You might need to run `npm prettier` or `make website` and then push again, @mzhaase ... the linter is failing on the build. ;-(

2024-11-13 14:04 UTC, mzhaase commented
I implemented the changes in a new commit.

2024-12-03 03:09 UTC, tanberry commented on website/integrations/services/hashicorp-vault/index.md
> +You should then be able to sign in via OIDC.
@mzhaase There's some weird formatting going on here.. if you look at the Deploy Preview, line 150 is mushed up on same line as 149. Do we still need 150? Did it get lost from somewhere else?

2024-12-03 03:11 UTC, tanberry commented on website/integrations/services/hashicorp-vault/index.md
> +You should then be able to sign in via OIDC.
<img width="724" alt="Screenshot 2024-12-02 at 9 10 51 PM" src="https://github.com/user-attachments/assets/30c6ab2b-4eba-40a2-b1e9-7025214198f1">

2024-12-17 19:14 UTC, tanberry approved these changes

2024-12-17 19:15 UTC, merged