New SMS provider, aka wrapper for outside API
goauthentik/authentik pull request #1595
Opened 2021-10-11 22:03 UTC by samip5

# Details
Extends #1476

## Changes
### New Features
* Adds feature which allows Authentik to call an outside API for SMS TOTP.

## Additional
Currently not sure how I can get the static files updated that it serves.

2021-10-12 18:09 UTC, BeryJu commented
can you try setting ```yaml
web:
  load_local_files: true
``` in your local.env.yml? Think I just missed adding that in the docs cause thats a relatively new setting

2021-10-12 19:06 UTC, samip5 commented
> > > > How would I show the options based on the provider? (Not used to your frontend framework.)
> > > 
> > > 
> > > you can just replace this part with an expression based on which provider is selected
> > > ```js
> > > label=${t`Twilio Account SID`}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > you can also leave the label as is, I don't mind adding that later myself
> > 
> > 
> > Could you show an example of such expression? I want to at least change the generic ones to that.
> 
> For example, you can do
> 
> ```
> label=${this.instance?.provider === ProviderEnum.Twilio  ? t`Twilio foo` : t`Something foo`}}
> ```
> 
> which is not really that clean, I'd probably add another function somewhere to switch or w/e

It doesn't even like that syntax.

2021-10-13 08:20 UTC, samip5 commented
I think it's ready for review, I know that docs haven't been updated.

2021-10-13 20:02 UTC, BeryJu requested changes

2021-10-14 08:13 UTC, merged