Feat: Add Mailcow oauth source
goauthentik/authentik pull request #2380
Opened 2022-02-24 08:15 UTC by dorianim

# Details
* **Does this resolve an issue?**
Resolves #2369

## Changes
### New Features
* Adds Mailcow as an OAuth source

2022-02-26 14:24 UTC, BeryJu requested changes
Couple things missing;

- please run `make migrations` to create migrations for the new model
- please run `make` to format everything
- and finally run `make gen-build` to build the new API scheme

2022-02-26 16:51 UTC, dorianim commented
make migrations did not work for me, so I ran `manage.py makemigrations`

2022-02-26 21:31 UTC, BeryJu commented
Also I assume you tested this locally, could you add some basic tests like https://github.com/goauthentik/authentik/blob/master/authentik/sources/oauth/tests/test_type_discord.py ?

2022-02-27 12:45 UTC, dorianim commented
Tests should work, I'll also add some documentation

2022-02-27 13:08 UTC, dorianim commented
All done now :)

2022-02-27 13:12 UTC, BeryJu commented on authentik/sources/oauth/tests/test_type_mailcow.py
> +            provider_type="openidconnect",
`provider_type="mailcow",`

2022-02-27 13:20 UTC, dorianim commented
What did I do wrong with the website? I tried to add the mailcow doc to the menu in `sidebarsIntegrations.js` and the build fails.

2022-02-27 13:27 UTC, BeryJu commented
![image](https://user-images.githubusercontent.com/1932513/155884330-cdfb3ed1-e8f6-439a-91ca-65788b56a6a6.png)
that's probably why

2022-02-27 14:06 UTC, merged