website/integrations: Add Gitea Helm Chart Configuration
goauthentik/authentik pull request #3558
Opened 2022-09-08 01:31 UTC by bpanesar

# Details
* Adds documentation on how to configure Authentik in Gitea using the Gitea Helm Chart

## Changes
### New Features
* Adds documentation on how to configure Authentik in Gitea using the Gitea Helm Chart

2022-09-14 13:26 UTC, BeryJu requested changes
Small nitpicks, needs `make website` to fix formatting

2022-09-14 13:26 UTC, BeryJu commented on website/integrations/services/gitea/index.md
> +Authentik can be configured automatically in Gitea Kubernetes deployments via it's [Helm Chart](https://gitea.com/gitea/helm-chart/).
Nit: should be lowercased as stated here https://goauthentik.io/developer-docs/docs/writing-documentation#general-guidelines

2022-09-14 13:26 UTC, BeryJu commented on website/integrations/services/gitea/index.md
> +    - name: 'Authentik'
Same as above

2022-09-14 13:26 UTC, BeryJu commented on website/integrations/services/gitea/index.md
> +This is based on Authentik 2022.8.2, Gitea v17.2, and Gitea Helm Chart v6.0.1. Instructions may differ between versions.
Same as above

2022-09-14 13:26 UTC, BeryJu commented on website/integrations/services/gitea/index.md
> +    - name: 'Authentik'
Same as above

2022-09-15 01:33 UTC, bpanesar commented
> Small nitpicks, needs `make website` to fix formatting

Should I squash my

2022-09-15 08:24 UTC, merged