Add ability to choose a default authentication flow for a provider
goauthentik/authentik pull request #3696
Opened 2022-09-28 17:54 UTC by rissson

# Details
* **Does this resolve an issue?**
Resolves #3694

## Changes
### New Features
* Add ability to choose a default authentication flow for a provider

## Additional

Questions I ask myself:

* Does it make sense to have this for LDAP/Proxy providers?
* Is it okay not to specify a default authentication flow? My guess is yes, as it will fallback on the current behavior.

2022-09-30 18:52 UTC, BeryJu requested changes
mostly LGTM, the only changes requested are for phrasing, and changing some database constraints

2022-09-30 18:52 UTC, BeryJu commented on authentik/core/models.py
> +        blank=True,
```suggestion
```

2022-09-30 18:52 UTC, BeryJu commented on authentik/core/models.py
> +        on_delete=models.CASCADE,
```suggestion
        on_delete=models.SET_NULL,
        default=None,
```

2023-02-27 20:51 UTC, closed without merging

2023-03-02 15:05 UTC, Zegorax commented
@BeryJu What is missing in this PR in order to have it merged ?

2023-03-03 02:18 UTC, rissson commented
I still haven't applied his suggestions. I'll get around to it soon.

2023-03-15 12:43 UTC, Zegorax commented
@rissson Do you need any help to finish it?

2023-03-23 21:50 UTC, rissson commented
@BeryJu I applied your suggestions. Would it be possible to re-open this?

2023-03-23 21:55 UTC, BeryJu commented
![image](https://user-images.githubusercontent.com/1932513/227373346-73f8d686-7535-4b55-9842-c23bf1919289.png)
Github actually doesn't let me, but while I'm at it I'll disable stalebot for PRs as it doesn't really make sense

2023-03-23 22:21 UTC, BeryJu commented
You should be able to create a new PR with the same branch though