Added Komga OIDC and Calibre-Web LDAP SSO Documentation
goauthentik/authentik pull request #4139
Opened 2022-12-02 11:41 UTC by Avsynthe

## Changes
### New Features
* Adds SSO documentation for Komga and Calibre-Web

2023-02-17 15:12 UTC, BeryJu requested changes
Missing a couple minor things, also add the docs to the sidebar here https://github.com/goauthentik/authentik/blob/153bd3aaf1519eef7a7699e8b314b5652dbc8df1/website/sidebarsIntegrations.js

(Also normally it would be preferred to create a PR per service, just for the future)

2023-02-17 15:12 UTC, BeryJu commented on website/integrations/services/calibre-web/index.md
> +-   `ldapservice` is the username of the authentik admin user you'd like to use for Calibre-Web to connect.
Missing the FQDN of authentik, calibre and the ldap outpost (see https://goauthentik.io/integrations/services/jellyfin/#what-is-jellyfin)

2023-02-17 15:12 UTC, BeryJu commented on website/integrations/services/calibre-web/index.md
> +Create an application for Calibre-Web in authentik and follow the Forward auth documentation here https://goauthentik.io/docs/providers/proxy/forward_auth
Missing instructions for the LDAP application

2023-02-17 15:12 UTC, BeryJu commented on website/integrations/services/komga/index.md
> +-   Scopes: OpenID, Email and Profile
```suggestion
```
These scopes are the default so this is redundant

2024-11-03 18:33 UTC, OddMagnet commented
Found this PR while trying to add OAuth2 to Komga, will you fix the minor issues @Avsynthe ?
Or should I go ahead and create a seperate one for Komga?
(I'm a complete Authentik noob, so the most I can do is OAuth2 with what I found here, lol)

2024-12-20 22:34 UTC, Aterfax commented
FYI - the Komga documentation when followed appears to give "invalid_id_token" -  so there may be a need to update this with specifics for SpringBoot if something has changed.

2025-01-02 21:35 UTC, closed without merging