web/src: set required flag to false for user attributes
goauthentik/authentik pull request #6418
Opened 2023-07-28 21:53 UTC by tanberry

## Details
 On the Create user form, the field for Attributes is not required, so I removed the asterisk by editing `web/src/admin/users/UserForm.ts` to set required flag to `false`. 

## Changes

Attributes field on Create User no longer shown as Required (which it is not).

### New Features

n/a

### Breaking Changes

n/a

## Checklist

-   [ ] Local tests pass (`ak test authentik/`)
-   [ ] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [ ] The code has been formatted (`make web`)
-   [ ] The translation files have been updated (`make i18n-extract`)

If applicable

-   [ ] The documentation has been updated
-   [ ] The documentation has been formatted (`make website`)

2023-07-28 23:34 UTC, rissson approved these changes

2023-07-29 13:07 UTC, BeryJu requested changes
So this kinda works and kinda doesn't

Since we default to `{}` in L153, it'll work without changing anything. However the field is still technically required, as if that value is `null` there'll be an error

2023-07-29 16:33 UTC, tanberry commented
> So this kinda works and kinda doesn't
> 
> Since we default to `{}` in L153, it'll work without changing anything. However the field is still technically required, as if that value is `null` there'll be an error

@BeryJu when you say "if that value is null" which value do you mean? Because I have created new Users without adding any attributes, so you must not mean the value entered into the Attributes section/field... when you have time I'd love to learn more about this... and actually @baloc and I will need to edit the new Create User docs if that Attributes field is indeed required.

2023-08-23 17:23 UTC, BeryJu approved these changes
We can just intercept the potential null value and set it to the default empty user attributes

cc @kensternberg-authentik lmk if there's a cleaner way to do this

2023-08-26 19:13 UTC, merged