Integration for sonar-qube
goauthentik/authentik pull request #7167
Opened 2023-10-13 18:50 UTC by senare

Add doc for integration SonarQube

2023-10-17 15:52 UTC, rissson requested changes

2023-10-17 16:06 UTC, BeryJu commented on website/integrations/services/sonar-qube/index.md
> +- SAML user email attribute : email
for `<download from authentik>` you might want to not use < and > since that gets interpreted as an HTML element

2023-10-17 17:30 UTC, rissson commented on website/integrations/services/sonar-qube/index.md
> +- SAML user email attribute : email
I updated my suggestion

2023-10-18 09:29 UTC, senare commented on website/integrations/services/sonar-qube/index.md
> +- SAML user email attribute : email
i guess not .. let me update my deployment and I will come back and update if it still works !

2023-10-18 09:29 UTC, senare commented on website/integrations/services/sonar-qube/index.md
> +- SAML user email attribute : email
thanx!

2023-10-19 09:45 UTC, senare commented
I did run 

$ make website-lint-fix

but it wont say what's not linted nor did it correct it, any advice  ?

2023-10-20 16:12 UTC, rissson commented
`make website-lint-fix` should edit the files already:
```
diff --git a/website/integrations/services/sonar-qube/index.md b/website/integrations/services/sonar-qube/index.md
index 650a9eb0e..a957c0613 100644
--- a/website/integrations/services/sonar-qube/index.md
+++ b/website/integrations/services/sonar-qube/index.md
@@ -73,18 +73,17 @@ resource "authentik_application" "application_sonar-qube" {

 ```

-
 ## SonarQube

 Navigate to Administration -> Configuration -> Authentication -> Saml

 Input these Values

-- Application ID: https://sonarqube.company/saml2/metadata
-- Provider Name: authentik
-- Provider ID: https://authentik.company/
-- SAML login url: https://authentik.company/application/saml/sonarqube/sso/binding/redirect/
-- Identity provider certificate: Download it from authentik
-- SAML user login attribute: login
-- SAML user name attribute: name
-- SAML user email attribute: email
+-   Application ID: https://sonarqube.company/saml2/metadata
+-   Provider Name: authentik
+-   Provider ID: https://authentik.company/
+-   SAML login url: https://authentik.company/application/saml/sonarqube/sso/binding/redirect/
+-   Identity provider certificate: Download it from authentik
+-   SAML user login attribute: login
+-   SAML user name attribute: name
+-   SAML user email attribute: email
```

2023-10-24 11:05 UTC, senare commented on website/integrations/services/sonar-qube/index.md
> +- SAML user email attribute : email
Sry, I finally got around to update and test my configuration, and ofc it works !

Using the default SAML mappings makes the configuration shorter only reason I didn't do it from the beginning is I didn't think it were correct. Don't know if thats a short coming on me or if maybe documentation could be improved some where for how that works ?

2023-10-24 17:18 UTC, rissson commented
Ah yes I forgot about this, you need to add an entry to the sidebar in the `website/sidebarsIntegrations.js` file for it to show up on the website.

2023-10-26 11:15 UTC, rissson requested changes

2023-10-26 11:15 UTC, rissson commented on website/sidebarsIntegrations.js
> +                        "services/sonar-qube/index",
```suggestion
                        "services/sonar-qube/index",
                        "services/sonarr/index",
                        "services/tautulli/index",
                        "services/weblate/index",
```
We're trying to keep this list sorted. Sorry about this, I should have mentioned it earlier.

2023-10-30 12:31 UTC, rissson approved these changes

2023-10-30 12:31 UTC, merged

2026-01-30 18:45 UTC, jader31 commented
I need help with this. The doc has a Terraform entry and not instructions about how to create app no Authentik.
I have time to update it on https://github.com/goauthentik/authentik/blob/main/website/integrations/development/sonar-qube/index.mdx just need to fix the instructions.