website/blog: draft for happy bday blog
goauthentik/authentik pull request #7408
Opened 2023-11-01 22:40 UTC by tanberry

Very drafty:

-- still need to get image in metadata to work
-- still need to actually read again when i am not exhausted
-- Jens and all please carefully review all of it, and especially the What's next section.

2023-11-01 23:35 UTC, kensternberg-authentik reviewed
Just some generic grammar things.

2023-11-01 23:35 UTC, kensternberg-authentik commented on website/blog/2023-11-1-happy-birthday-to-us/item.md
> +The tone and espirit of the company is one reason it’s so meaningful to celebrate our 1-year birthday; we can happily celebrate a hard year of doing things with full, enthusiastic engagement. At auth
Typo: "flourishs" -> "flourishes"

2023-11-01 23:35 UTC, kensternberg-authentik commented on website/blog/2023-11-1-happy-birthday-to-us/item.md
> +Going forward, we want to of course keep our focus on building features and supporting authentication protocols that our users want, but we have also identified several specific goals for this coming
Suggestion: The "... of course ..." kinda breaks the flow.  It works verbally, but read silently it feels a bit like a hiccup.

2023-11-02 12:47 UTC, rissson requested changes, later dismissed

2023-11-02 12:47 UTC, rissson commented on website/blog/2023-11-1-happy-birthday-to-us/item.md
> +Right at the end of our first year, we released our [Enterprise version](https://goauthentik.io/blog/2023-08-31-announcing-the-authentik-enterprise-release), with dedicated support. And just last wee
```suggestion
Right at the end of our first year, we released our [Enterprise version](https://goauthentik.io/blog/2023-08-31-announcing-the-authentik-enterprise-release), with dedicated support. And just last week, we rolled out one of the most important capabilities in an identity management platform: [RBAC](https://goauthentik.io/docs/user-group-role/access-control/) (role-based access control).
```

2023-11-02 12:47 UTC, rissson commented on website/blog/2023-11-1-happy-birthday-to-us/item.md
> +With a new team, come new processes. Someone has to decide which emoji to use for which infrastructure task that’s completed.
Did we?

2023-11-02 12:47 UTC, rissson commented on website/blog/2023-11-1-happy-birthday-to-us/item.md
> +Thanks for joining us on this celebration of our one-year birthday, and let us know any thoughts you might have. You can send an emial to hello@authentik.io, or find us on GitHub or Discord.
```suggestion
Thanks for joining us on this celebration of our one-year birthday, and let us know any thoughts you might have. You can send an email to hello@authentik.io, or find us on GitHub or Discord.
```

2023-11-02 14:07 UTC, tanberry commented on website/blog/2023-11-1-happy-birthday-to-us/item.md
> +Right at the end of our first year, we released our [Enterprise version](https://goauthentik.io/blog/2023-08-31-announcing-the-authentik-enterprise-release), with dedicated support. And just last wee
Wow, great catch, thank you.

2023-11-02 16:41 UTC, kensternberg-authentik approved these changes
Two [`polish`](https://conventionalcomments.org/#:~:text=Polish%20comments%20are%20like%20a%20suggestion%2C%20where%20there%20is%20nothing%20necessarily%20wrong%20with%20the%20relevant%20content%2C%20there%27s%20just%20some%20ways%20to%20immediately%20improve%20the%20quality.) level comments, but otherwise great.

2023-11-02 16:55 UTC, merged