Add Chronograf to website
goauthentik/authentik pull request #7766
Opened 2023-12-03 19:53 UTC by tomlawesome

Add Chronograf oauth integration to website.

## Details

Chronograf is not listed yet in integrations, but it's working well for me using their generic oauth and Authentik's oauth endpoints generated by simply creating an oauth provider.

---

## Checklist

-   [ ] Local tests pass (`ak test authentik/`)
-   [ ] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [ ] The code has been formatted (`make web`)
-   [ ] The translation files have been updated (`make i18n-extract`)

If applicable

-   [x] The documentation has been updated
-   [ ] The documentation has been formatted (`make website`)

2023-12-04 16:02 UTC, tanberry commented
Thanks so much @tomlawesome for this contribution! I'll do a copy-edit on the docs, and get a tech review on it.  Always nice to add more integrations.

2023-12-04 17:43 UTC, rissson requested changes

2023-12-09 14:19 UTC, tomlawesome commented on website/integrations/services/chronograf/index.md
> +![image](https://github.com/tomlawesome/authentik/assets/76453276/c14a4694-563b-4a94-9cd4-162c4e543bd7)
I'm not sure, sorry. Very new to pull requests!

2023-12-11 07:08 UTC, rissson requested changes
I missed it before, but you also need to add this page to `website/sidebarsIntegrations.js`, probably under the `Monitoring` category (the list is alphabetically sorted).

2023-12-11 07:08 UTC, rissson commented on website/integrations/services/chronograf/index.md
> +![image](https://github.com/tomlawesome/authentik/assets/76453276/c14a4694-563b-4a94-9cd4-162c4e543bd7)
Sure, no worries. What you can do is directly put the image under `website/integrations/services/chronograf/login.png` and use `![](./login.png)` to show the image.

2024-02-18 17:31 UTC, PierreBtz commented
Hey, thanks a lot for this PR, this helped a lot.

However I had to add `USE_ID_TOKEN=true` for the setup to properly work (as per https://docs.influxdata.com/chronograf/v1/administration/managing-security/#jwks-signature-verification-optional).

2024-02-23 18:57 UTC, tanberry commented
Hi @tomlawesome can you take a look at the last few points/edits, and then see about adding the tip that @PierreBtz made? Also, you'll need to run `make website` or `make website-lint-fix` before pushing your final commit, so that the build check for linting passes.

Apologies we let this one sit for a bot; we are looking forward to your reply and getting it merged, thanks!

2024-12-30 22:29 UTC, closed without merging