website/integrations: Add Synology DSM
goauthentik/authentik pull request #8081
Opened 2024-01-07 21:55 UTC by bobvmierlo

## Details

Add Synology DSM as a client, using OpenID

---

## Checklist
-   [X] The documentation has been updated
-   [X] The documentation has been formatted

2024-01-25 23:47 UTC, tanberry commented
Hi @bobvmierlo thanks so much for adding Synology's DSM to the list of integrations. I'll give it a quick copy-edit, and then after you made any suggested changes can you also please be sure to run the `make website` command, which runs our linter and will clear up the build failure for "lint-prettier" on current PR?

2024-01-26 00:23 UTC, tanberry requested changes
Just formatting suggestions, and the request to run `make website` before pushing these or other changes. Thanks again for this contribution!

2024-01-26 00:23 UTC, tanberry commented on website/integrations/services/synology-dsm/index.md
> +8. Name: Authentik
I'd suggest that you make all of these options into bullet points...

2024-01-26 14:44 UTC, tanberry commented
Hi @bobvmierlo I forgot to mention, you will also need to edit the `sidebarsIntegrations.js` file, in order for the new Integration to appear in the ToC on left side. Let us know if you have any questions at all, and thanks again for this contribution!

2024-01-26 17:18 UTC, bobvmierlo commented
Added the sidebar changes and ran make website command

2024-01-26 20:14 UTC, tanberry commented
Thanks @bobvmierlo for running the linter; that part of build now passes.

Just 2 more clean-up tasks, then we can merge:

1. I think you only need two files in the PR, the new document for how to add Synology and the sidebar one. What are the other 58 files? Can you remove those from the PR, please?
2. For lines 51-56, you still need to make those into bullet items... I only did the first two for you. ;-)

2024-01-26 20:27 UTC, bobvmierlo commented
> Thanks @bobvmierlo for running the linter; that part of build now passes.
> 
> Just 2 more clean-up tasks, then we can merge:
> 
> 1. I think you only need two files in the PR, the new document for how to add Synology and the sidebar one. What are the other 58 files? Can you remove those from the PR, please?
> 2. For lines 51-56, you still need to make those into bullet items... I only did the first two for you. ;-)

Tried to remove the unneeded files, they where a accidental addition due to running the make website command. Not sure if it worked though, might need some help with that. I'm not a git expert.

2024-01-26 20:41 UTC, tanberry commented
Yeah, git can be a bit wild at times, haha. I have an entire repo just to hold my cheat-sheets for git. 

Looks like you figured out how to remove the extra files, though. 

It's rebuilding now, then I'll merge. Thanks again for your contribution and your perseverance!

2024-01-26 21:14 UTC, tanberry approved these changes
I'll make the alphabetical change later.

2024-01-26 21:14 UTC, merged