documentation: Add description for custom enrollment to azure ad
goauthentik/authentik pull request #8392
Opened 2024-02-01 20:34 UTC by tograss

## Details
Add a description how to setup a custom enrollment flow and mapping of attributes from azure ad
---

## Checklist
-   [x] The documentation has been updated
-   [x] The documentation has been formatted (`make website`)

2024-02-12 18:44 UTC, tanberry commented
HI @tograss thanks for the contribution! Can you add an introductory sentence or two to your new section in the docs, explaining what the use case is, why you'd want to do this, etc., please? Then we can get a tech review and hopefully merge soon afterwards.

This also reminds me that I need to go through our Docs and change Azure AD to Entra ID... fun.

2024-02-15 15:00 UTC, tograss commented
Hi @tanberry I added a small Introduction .

2024-02-15 19:34 UTC, tanberry commented
Thanks so much @tograss . Sounds like a powerful capability. I have one more small edit, then we will get a technical review down by the engineers. Thanks again for your contribution!

2024-02-23 18:32 UTC, tanberry requested changes
A couple more small issues, when you have time.

2024-03-01 09:42 UTC, tograss commented on website/integrations/sources/azure-ad/index.md
> +Via the following process you can enroll your users without interaction or directly control the mapping azure attribute to authentik
Looks good to me 👍

2024-03-01 15:50 UTC, tanberry commented
OK cool, thanks for reviewing @tograss ! Do you want me to add those edits (I'll be marked as co-contributor), or you (you will get full credit for PR)? I vote you do it and get full credit,  but up to you, I don't know how busy you are...

2024-03-04 14:53 UTC, tograss commented
@tanberry Thanks for your suggestion but I'm fine with you co-authoring :-) Thanks again to the whole authentik team for your work.

2024-03-04 17:20 UTC, tanberry approved these changes
Thank so much for these contributions, @tograss!

2024-03-06 22:42 UTC, merged