Add documentation for OIDC setup with Paperless-ngx
goauthentik/authentik pull request #8538
Opened 2024-02-15 18:08 UTC by girlpunk

## Details

Add documentation for setting up OIDC authntication for Paperless-ngx

---

## Checklist

-   [ ] Local tests pass (`ak test authentik/`)
-   [ ] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [ ] The code has been formatted (`make web`)

If applicable

-   [X] The documentation has been updated
-   [ ] The documentation has been formatted (`make website`)

2024-02-15 18:31 UTC, rissson commented
Heya, thanks for your contribution! You also need to add the new documentation to `website/sidebarIntegrations.js`. I'll be going through migrating my paperless-ngx to using OIDC soon-ish, I'll review this then.

2024-02-15 19:14 UTC, tanberry reviewed
Thanks so much @girlpunk for this contribution. I made a few word edits, @marc will do the technical review. We appreciate your contribution!

2024-02-15 19:14 UTC, tanberry commented on website/integrations/services/paperless-ngx/index.md
> +> Paperless-ngx is an application that indexes your scanned documents and allows you to easily search for documents and store metadata alongside your documents. It was a fork from paperless-ngx, in t
```suggestion
> Paperless-ngx is an application that indexes your scanned documents and allows you to easily search for documents and store metadata alongside your documents. It was a fork from paperless-ngx, in turn a fork from the original Paperless, neither of which are maintained any longer.
```

2024-02-15 19:14 UTC, tanberry commented on website/integrations/services/paperless-ngx/index.md
> +## Authentik Configuration
```suggestion
## authentik Configuration
```

2024-02-15 19:14 UTC, tanberry commented on website/integrations/services/paperless-ngx/index.md
> +## Paperless
```suggestion
## Paperless Configuration
```

2024-02-15 19:14 UTC, tanberry commented on website/integrations/services/paperless-ngx/index.md
> +Add the following environment variables to your Paperless-ngx setup. If you are using docker-compose, then add the following to your docker-compose.yml file:
```suggestion
Add the following environment variables to your Paperless-ngx setup. If you are using Docker Compose, then add the following to your docker-compose.yml file:
```

2024-02-15 19:14 UTC, tanberry commented on website/integrations/services/paperless-ngx/index.md
> +To add Authentik authentication to an existing user, log in to Paperless with local authentication, click the profile icon in the top-right, click My Profile, then Connect new social account.
```suggestion
To add authentik authentication to an existing user, log in to Paperless with local authentication, click the profile icon in the top-right, click My Profile, then Connect new social account.
```

2024-02-26 08:08 UTC, rissson requested changes

2024-02-26 08:08 UTC, rissson commented on website/integrations/services/paperless-ngx/index.md
> +            "server_url": "https://authentik.company/application/o/authorize/"
```suggestion
            "server_url": "https://authentik.company/application/o/paperless/.well-known/openid-configuration"
```

2024-02-28 10:29 UTC, rissson approved these changes

2024-02-28 10:47 UTC, merged