Update index.md
goauthentik/authentik pull request #8683
Opened 2024-02-25 18:06 UTC by Webstijlen

The option needs to be selected, or else auth fails

## Details

REPLACE ME

---

## Checklist

-   [ ] Local tests pass (`ak test authentik/`)
-   [ ] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [ ] The code has been formatted (`make web`)

If applicable

-   [ ] The documentation has been updated
-   [ ] The documentation has been formatted (`make website`)

2024-02-26 19:45 UTC, tanberry requested changes
Thanks @Webstijlen for that important clarification. Only one small nit (format the name of flow), please.

Can you also add a Head 2 (##) Right above Step 1, titled "authentik configuration"? I see now that Portainer and Rancher (other integrations listed beside Proxmox) do not follow our template either. Take a look at the one for ArgoCD... that's what we need, two separate areas for authentik setup and for the integrating product setup.

Let us know of questions, thanks again!

2024-02-26 19:45 UTC, tanberry commented on website/integrations/services/proxmox-ve/index.md
> +-   Authentication Flow: default-authentication-flow (Welcome to authentik!)
```suggestion
-   Authentication Flow: `default-authentication-flow` (Welcome to authentik!)
```

2024-03-07 18:50 UTC, BeryJu requested changes
This option should not affect whether authentication succeeds or fails, and if it does that's a bug. Could you provide the logs/error messages that happen when this option is not selected and you try to authenticate?

2024-04-04 15:37 UTC, BeryJu commented
Having now setup proxmox myself and having set it up with OIDC, this change is not required

2024-04-04 15:37 UTC, closed without merging