website/integrations: add outline knowledge base
goauthentik/authentik pull request #8786
Opened 2024-03-03 13:49 UTC by fallenhitokiri

## Details

Adds instructions to setup OIDC for outline.

---

## Checklist

If applicable

-   [x] The documentation has been updated
-   [x] The documentation has been formatted (`make website`)

2024-03-11 21:20 UTC, tanberry commented
Thanks so much @fallenhitokiri for this contribution! I made a few suggestions/edits, and also you will need to edit the `sidebarintegrations.js` file to add Outline to the left nav pane, please. Let us know if you have any questions; we look forward to merging this as soon as those few fixes are made. Thanks again!

2024-03-11 21:20 UTC, tanberry requested changes

2024-03-11 21:20 UTC, tanberry commented on website/integrations/services/outline/index.md
> +Create an OAuth2/OpenID provider with the following parameters:
```suggestion

## authentik configuration

1. Create an OAuth2/OpenID provider with the following parameters:
```

2024-03-11 21:20 UTC, tanberry commented on website/integrations/services/outline/index.md
> +Note the Client ID and Client Secret values.
```suggestion
2. Note the Client ID and Client Secret values.
```

2024-03-11 21:20 UTC, tanberry commented on website/integrations/services/outline/index.md
> +## Outline
```suggestion
## Outline configuration
```

2024-03-11 21:20 UTC, tanberry commented on website/integrations/services/outline/index.md
> +You need to set the following `env` Variables for Docker based installations.
```suggestion
You need to set the following `env` variables for Docker-based installations.
```

2024-03-11 21:20 UTC, tanberry commented on website/integrations/services/outline/index.md
> +Set the following values:
```suggestion
1. Set the following values:
```

2024-03-15 15:36 UTC, tanberry commented
Hi again @fallenhitokiri will you have a chance to make the requested changes, and then we can merge it? Or, if you're ok with it, I can make the changes and merge it.

2024-03-17 18:39 UTC, fallenhitokiri commented
@tanberry I got started on the changes and expect to land them tomorrow or Tuesday. (I didn’t get a notification and only saw your comments by accident when checking my GitHub inbox)

I used the HedgeDoc documentation as a template. Would some of the changes suggested here also apply to the HedgeDoc doc?

2024-03-21 14:20 UTC, tanberry commented
Hi @fallenhitokiri thanks for the update, and I will take a look at the HedgeDoc docs as well. We do have a proper template there in the repo, but we need to do a better job of making it easier to find, for sure.

We will look forward to your changes; let me know if we can help!

2024-04-01 20:04 UTC, tanberry approved these changes
Thanks @fallenhitokiri !!

2024-04-01 20:05 UTC, merged