Update Nextcloud OIDC secret size limitation
goauthentik/authentik pull request #9139
Opened 2024-04-04 18:27 UTC by Fymyte

## Details

The previous limitation on [oidc secret being restricted to 64 character](https://github.com/nextcloud/user_oidc/issues/405) has been fixed. Update the note

-   [X] The documentation has been updated

2024-04-05 20:19 UTC, tanberry commented on website/integrations/services/nextcloud/index.md
> +There were an issue in the Nexcloud OIDC app that was [limiting the size of the secret ID](https://github.com/nextcloud/user_oidc/issues/405) token to 64 characters. This issue has been fixed in dece
```suggestion
There were an issue in the Nexcloud OIDC app that was [limiting the size of the secret ID](https://github.com/nextcloud/user_oidc/issues/405) token to 64 characters. This issue was fixed in December 2023, so make sure you update to the latest version of the [OpenID Connect user backend](https://apps.nextcloud.com/apps/user_oidc) application.
```

2024-04-05 20:21 UTC, tanberry requested changes
Thanks so much for updating these integrations docs, @Fymyte ! A few small nits about capitalization; as soon as those are fixed LGTM!

2024-04-08 09:58 UTC, BeryJu commented on website/integrations/services/nextcloud/index.md
> +There were an issue in the Nexcloud OIDC app that was [limiting the size of the secret ID](https://github.com/nextcloud/user_oidc/issues/405) token to 64 characters. This issue was fixed in December
```suggestion
There were an issue in the Nextcloud OIDC app that was [limiting the size of the secret ID](https://github.com/nextcloud/user_oidc/issues/405) token to 64 characters. This issue was fixed in December 2023, so make sure you update to the latest version of the [OpenID Connect user backend](https://apps.nextcloud.com/apps/user_oidc) application.
```

2024-04-08 09:59 UTC, BeryJu approved these changes

2024-04-08 10:01 UTC, Fymyte commented
Thanks didn't spot the missing t before 😅

2024-04-08 10:09 UTC, merged