Add tip to solve hashed groups configuring OAuth2 on Nextcloud
goauthentik/authentik pull request #9153
Opened 2024-04-05 13:53 UTC by lucaam

## Details

I had to play a bit to figure this out and it is not mentioned so I think it is useful to add the guidance to users that are trying to set OAuth2 configuration on Nextcloud.

---

## Checklist

-   [ ] Local tests pass (`ak test authentik/`)
-   [ ] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [ ] The code has been formatted (`make web`)

If applicable

-   [x] The documentation has been updated
-   [x] The documentation has been formatted (`make website`)

2024-04-05 20:16 UTC, tanberry commented on website/integrations/services/nextcloud/index.md
> +    If groups are hashed, ence you are not assigned to the admin group, you can try to uncheck this.
```suggestion
    To avoid your group assignment being a hash value, deselect **Use unique user ID**.
```

2024-04-05 20:17 UTC, tanberry requested changes
Thanks @lucaam for this helpful tip. Pease review my suggested wording, and make sure it still says what you intended before accepting the suggestion.

2024-04-05 20:18 UTC, tanberry commented
It also looks like you will need to run `make website` before pushing further commits to the PR... the lint-prettier check is failing in the build process. Let us know if you have any questions!

2024-04-05 20:32 UTC, lucaam commented
@tanberry Thanks for the suggestion, I think is way better now. I also executed `make website` to properly lint the code!

2024-04-11 17:04 UTC, tanberry approved these changes
Thanks @lucaam !

2024-04-11 17:04 UTC, merged