add doc for Custom LDAP Property Mapping
goauthentik/authentik pull request #9524
Opened 2024-04-30 04:43 UTC by ChenWenBrian

## Details

Add detailed steps for users to know how to add custom LDAP Property Mapping, cause this question is usually asked and got no answer.

---

## Checklist

-   [ ] Local tests pass (`ak test authentik/`)
-   [ ] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [ ] The code has been formatted (`make web`)

If applicable

-   [x] The documentation has been updated
-   [x] The documentation has been formatted (`make website`)

2024-04-30 10:07 UTC, tanberry commented
Thanks very very much for this contribution, @ChenWenBrian ! We definitely need more procedural docs (the How To, with steps, kind of docs), so this is a great addition.

I'll make some edits (grammar and style), then after you make those changes please be sure to run either `make website` or `npm run prettier` before you push the chanes. The build is currently failing on `lint_prettier`.

Thanks again!

2024-04-30 20:06 UTC, tanberry requested changes
Thanks so much @ChenWenBrian for these steps, it is great to have more procedural/How To docs.

I made quite a few copy-edits, but I made then as Suggestions so that you can easily accept them. Let me know if you have any questions.

Also, please be sure to run `make website` or `npm run prettier` before you push your changes, so that the build checks pass.

2024-04-30 20:06 UTC, tanberry commented on website/docs/property-mappings/index.md
> +5. Type `Expression` which will get value from LDAP source. e.g. `return list_flatten(ldap.get("displayName"))`.
```suggestion
5. In the **Expression**  field enter Pythin expressions to retrieve the value from LDAP source. For example `return list_flatten(ldap.get("displayName"))`.
```

2024-04-30 20:06 UTC, tanberry commented on website/docs/property-mappings/index.md
> +`list_flatten(["input string array"])` will convert string array to single string. If you are not sure whether the ldap field is an array or not, you may map the field to any `attributes.xxx` and the
```suggestion
`list_flatten(["input string array"])` will convert a string array to a single string. If you are not sure whether the LDAP field is an array or not, you can map the field to any `attributes.xxx` and then check the sync result in authentik UI.
```

2024-04-30 20:24 UTC, tanberry commented
Hi again, thanks for the speedy fixes. After checking on a few technical details with @BeryJu we think this content might actually better belong on our documentation about LDAP sources, but I want to look at it again tomorrow and get back to you. Wherever it ends up, we very much appreciate having it added to the docs.

2024-04-30 20:32 UTC, ChenWenBrian commented
Hi @tanberry , thanks for your help. I accepted all your changes and fixed a few typos.

I haven't prepare a dev environment for this project, just update the doc from github UI. so, hope this won't bring too much trouble🙏

2024-05-15 21:17 UTC, tanberry commented
Hi again @ChenWenBrian apologies for my delay. We do want to move this content to a different section in the docs; we think it would fit better here: https://docs.goauthentik.io/docs/sources/ldap/#property-mappings

Let me know if you want to do this yourself (either in this PR or in a new one). Or if not, I can move it. Either way, thank you for adding this steps!

2024-05-16 06:21 UTC, ChenWenBrian commented
@tanberry please help to move the content, cause i'm not familiar with the procedure, thanks

2024-06-18 21:20 UTC, tanberry commented
Closing this one since the work is now done in https://github.com/goauthentik/authentik/pull/10158. Thanks @ChenWenBrian!

2024-06-18 21:20 UTC, closed without merging