docs: add gitlab oidc guide
goauthentik/authentik pull request #9740
Opened 2024-05-15 13:29 UTC by motey

## Details

Adding a guide to connect GitLab via OIDC (alternative to SAML which is the only guide at the moment)

Discussed in:

https://github.com/goauthentik/authentik/issues/8175

---

## Checklist

-   [ ] Local tests pass (`ak test authentik/`) <- not applicable; only doc changes
-   [ ] The code has been formatted (`make lint-fix`) <- not applicable; only doc changes

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`) <- not applicable; only doc changes

If changes to the frontend have been made

-   [ ] The code has been formatted (`make web`) <- not applicable; only doc changes

If applicable

-   [x] The documentation has been updated
-   [x] The documentation has been formatted (`make website`) <- Yes, but very unsure about this. should that not happen on "server"-side (github actions) in a controlled environment. Needed to install a lot of stuff on my machine for that :D not very contributor friendly

2024-05-16 08:40 UTC, motey commented on website/integrations/services/gitlab/index.md
> +Paste the following block in your `gitlab.rb` file, after replacing the placeholder values from above. The file is located in `/etc/gitlab`.
Good point, i just copied the sentence from the older SAML guide. Fixed it in the SAML guide as well with https://github.com/goauthentik/authentik/pull/9740/commits/de2d1df4430d629601e08cc6faf88ce71aca8958

2024-05-21 10:06 UTC, rissson approved these changes

2024-06-11 14:59 UTC, dominic-r requested changes

2024-06-11 15:09 UTC, motey commented on website/integrations/services/gitlab/index.md
> +The following placeholders will be used:
But the scope is the current chapter. And there is nothing defined in this scope. 
In the real world people will jump to this chapter and not read everything first.

2024-06-11 20:27 UTC, motey commented on website/integrations/services/gitlab/index.md
> +The following placeholders will be used:
>  Placeholders are not defined twice on other pages

Aint true in my world;
see https://docs.goauthentik.io/integrations/services/nextcloud/#openid-connect-auth vs https://docs.goauthentik.io/integrations/services/nextcloud/#saml-auth
If i am remembering correct, this is also what i took as template. And i just took the time to browse through all integrations docs. For now Nextcloud is the only one with 2 integration options. So i am not sure on what your statement is based. Could you provide an example?

> To be honest that's not really our problems if users are unable to read things

Ok, fair enough that is an opinion. But what is the advantage of having it only on the top and what is the disadvantage of defining it twice to have chapters to be self-consistent?

2024-06-18 18:29 UTC, tanberry requested changes
Thanks so much for this PR! And apologies; looks like I starting reviewing it weeks ago but never submitted it, so it has been sitting in Pending mode for a while, sorry.

2024-06-18 18:29 UTC, tanberry commented on website/integrations/services/gitlab/index.md
> +The following placeholders will be used:
Yeah, let's leave the placeholders and the Placeholder section for now...

2024-06-21 10:59 UTC, motey commented
@tanberry sorry, i am a little bit confused, whats the state of this PR is now and whose turn it is now :) maybe you can help out. thanks.

2024-07-03 21:41 UTC, tanberry approved these changes
Thanks again @motey and it's me that needs to apologize for not getting back to this earlier! Let's merge!

2024-07-03 21:41 UTC, merged