website/integrations: minio: configure openid on web
goauthentik/authentik pull request #9874
Opened 2024-05-27 02:44 UTC by dominic-r

## Details

closes #9873 

slight fixes on minio integration docs and documents configuration via web interface

---

## Checklist

-   [ ] Local tests pass (`ak test authentik/`)
-   [ ] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [ ] The code has been formatted (`make web`)

If applicable

-   [ ] The documentation has been updated
-   [ ] The documentation has been formatted (`make website`)

2024-05-27 11:37 UTC, rissson approved these changes

2024-06-11 14:05 UTC, tanberry requested changes
A few nits, mostly with formatting, thanks so much for this contribution!

2024-06-18 18:34 UTC, tanberry approved these changes
Thanks @4d62 ! I hope by merging this we don't cause conflicts in your other open PRs... I guess you can re-sync with main.

2024-06-18 18:38 UTC, tanberry commented
Oppps I just saw that the lint-prettier build check failed. Can you take a look, please?

2024-07-03 15:54 UTC, merged