website/docs: add docs for configuring Facebook as a source
goauthentik/authentik pull request #9884
Opened 2024-05-27 16:32 UTC by tanberry

Draft ready for review. 

Notes to be aware of:
-- the exact process for creating the FB app and configuring its Login Settings is based on the walk-through Jens and I did, and might not cover every step or alternative processes for creating the app, configuring Login, and publishing the app.
-- It wold be great if we could get community members who want to use FB as a source to double-check these docs, and open a PR with any fixes. I can ask on Discord.

-   [ ] The documentation has been updated
-   [ ] The documentation has been formatted (`make website`)

2024-05-27 17:23 UTC, rissson requested changes

2024-05-27 17:36 UTC, tanberry commented on website/docs/sources/facebook/index.md
> +8. On the **Facebook Login settings** in the **Valid OAuth redirect URIs** field enter your authentik instance URL, and click **Save**.
Ah, thank you @rissson. The `authentik.company` part would be whatever their domain is, right, so if I show an example, I want to make sure that is a variable.

And.. would that be called specifically a URL, or should I use the broader term URI?

2024-05-28 13:07 UTC, rissson commented on website/docs/sources/facebook/index.md
> +8. On the **Facebook Login settings** in the **Valid OAuth redirect URIs** field enter your authentik instance URL, and click **Save**.
> Ah, thank you @rissson. The `authentik.company` part would be whatever their domain is, right, so if I show an example, I want to make sure that is a variable.

It already is in the `Preparation` section

> And.. would that be called specifically a URL, or should I use the broader term URI?

URL is fine.

2024-05-28 13:11 UTC, rissson approved these changes

2024-05-28 14:41 UTC, merged