website/integrations: gitlab: update certificate key pair location and specify sha
goauthentik/authentik pull request #9925
Opened 2024-05-31 01:34 UTC by 4d62

## Details

closes #9924 

---

## Checklist

-   [ ] Local tests pass (`ak test authentik/`)
-   [ ] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [ ] The code has been formatted (`make web`)

If applicable

-   [ ] The documentation has been updated
-   [ ] The documentation has been formatted (`make website`)

2024-05-31 09:33 UTC, BeryJu commented on website/integrations/services/gitlab/index.md
> +To get the value for `idp_cert_fingerprint`, navigate to the admin interface's _System_ section and select _Certificates_. Then, expand the chosen certificate and copy the SHA1 Certificate Fingerprin
```suggestion
To get the value for `idp_cert_fingerprint`, navigate to the Admin interface, expand the  _System_ section and select _Certificates_. Then, expand the selected certificate and copy the SHA1 Certificate Fingerprint.
```

2024-06-11 13:11 UTC, tanberry requested changes
Thanks so much for this correction! Just a not on the formatting; as soon as that is changed let's get this merged.

2024-06-11 13:11 UTC, tanberry commented on website/integrations/services/gitlab/index.md
> +To get the value for `idp_cert_fingerprint`, navigate to the Admin interface, expand the  _System_ section and select _Certificates_. Then, expand the selected certificate and copy the SHA1 Certifica
We have moved to use bold text for UI components (field names, labels, etc) and italics for variables/placeholder values. We have a PR for a new Style Guide... I need to get that finished and published.

2024-06-11 20:08 UTC, tanberry approved these changes
Thanks! Though it looks like the `lint-prettier` build check is failing... can you run prettier again and push?

2024-06-12 21:37 UTC, merged